### ISSUE TITLE
 what is the ultimate functionality and outcome achieved by this project？

### ISSUE THREAD

**Issue by SunshineDHW** [sherwinbahmani/ynet_adaptive#5]
On the basis of the original paper's code, you introduced the Y-net structure. What is the purpose of introducing the Y-net structure? In other words, what is the ultimate functionality and outcome achieved by this project?

**Comment by sherwinbahmani** [comment]
Hi,

This repo provides an additional experiment on SDD using the Y-Net architecture. The goal is to compare our modular adaptation strategy against the standard fine-tuning of the entire model for low-shot transfer on another dataset and model architecture.

**Comment by SunshineDHW** [comment]
Thank you for your response. In other words, the Y-Net architecture is used for a comparative experiment with  your original model architecture, rather than being integrated with it. Is this correct?

**Comment by sherwinbahmani** [comment]
The only comparison here is: Y-Net architecture vs. Y-Net architecture with our modular adaptation
The Y-Net architecture is not compared with our original model architecture but just used to ablate our design choice on another backbone.

**Comment by SunshineDHW** [comment]
Thank you for your patient explanation.
